# Use a lightweight Python image
FROM python:3.10-slim

# Set working directory
/server

# Copy dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy rest of the application
COPY . .

# Expose default port for Hugging Face Spaces
EXPOSE 7860

# Command to start FastAPI app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "7860"]
